apiVersion: v1
kind: Service
metadata:
  name: finance-app-service
spec:
  selector:
    app: finance-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
  type: NodePort