name: Test and build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run linting
        run: |
          flake8 ./src

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Docker tag
        id: version
        run: |
          VERSION=v$(date + "%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build docker image
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USER }}/finance-app:${{ env.VERSION }}
      
      - name: Push docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/finance-app:${{ env.VERSION }}